version: '3'

services:
  database:
    container_name: database
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=cloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: 'cloud-service-backend:latest'
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=cloud
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    depends_on:
      - database
    ports:
      - "8081:8081"

volumes:
  postgres-data: